package ooxmlpatch

import (
	"regexp"
	"strings"

	"github.com/paper-format-checker/backend/internal/core/ooxmlpkg"
)

var (
	commentRangeElement     = regexp.MustCompile(`(?s)<w:commentRange(?:Start|End)\b[^>]*/>`)
	commentReferenceElement = regexp.MustCompile(`<w:commentReference\b[^>]*/>`)
	trackedInsertionElement = regexp.MustCompile(`(?s)<w:(?:ins|moveTo)\b[^>]*>(.*?)</w:(?:ins|moveTo)>`)
	trackedDeletionElement  = regexp.MustCompile(`(?s)<w:(?:del|moveFrom)\b[^>]*>.*?</w:(?:del|moveFrom)>`)
	commentsRelationship    = regexp.MustCompile(`(?s)<Relationship\b[^>]*\bType="[^"]*/comments"[^>]*(?:/>|>\s*</Relationship>)`)
	commentsContentType     = regexp.MustCompile(`(?s)<Override\b[^>]*\bPartName="/word/comments\.xml"[^>]*(?:/>|>\s*</Override>)`)

	// TOC bookmark patterns: __RefHeading___Toc bookmarks are generated by
	// Word for TOC hyperlinks referencing headings with built-in outline levels.
	// After template-in-place repair these become orphaned because the heading
	// structure of the student paper differs from the template skeleton.
	tocBookmarkStartRe = regexp.MustCompile(`<w:bookmarkStart w:id="(\d+)" w:name="__RefHeading___Toc\d+"/>`)
	bookmarkEndRe      = regexp.MustCompile(`<w:bookmarkEnd w:id="(\d+)"/>`)
)

func FinalizeReviewMarkup(pkg *ooxmlpkg.DocxPackage) int {
	if pkg == nil {
		return 0
	}
	changed := 0
	for _, name := range pkg.Names() {
		if !strings.HasPrefix(name, "word/") || !strings.HasSuffix(name, ".xml") {
			continue
		}
		if isProtectedAnnotationPart(name) {
			continue
		}
		content, ok := pkg.Get(name)
		if !ok {
			continue
		}
		updated := finalizeReviewXML(string(content))
		if updated != string(content) {
			pkg.Set(name, []byte(updated))
			changed++
		}
	}
	return changed
}

func isProtectedAnnotationPart(name string) bool {
	base := strings.ToLower(name)
	return strings.HasPrefix(base, "word/comments") ||
		base == "word/footnotes.xml" ||
		base == "word/endnotes.xml"
}

func finalizeReviewXML(content string) string {
	content = trackedDeletionElement.ReplaceAllString(content, "")
	content = trackedInsertionElement.ReplaceAllString(content, "$1")
	return content
}

// RemoveComments is intentionally separate from FinalizeReviewMarkup.
// Callers may remove comments that belong to a template skeleton, while
// in-place repairs must preserve comments from the student's source paper.
func RemoveComments(pkg *ooxmlpkg.DocxPackage) int {
	if pkg == nil {
		return 0
	}
	changed := 0
	for _, name := range pkg.Names() {
		if !strings.HasPrefix(name, "word/") || !strings.HasSuffix(name, ".xml") {
			continue
		}
		content, ok := pkg.Get(name)
		if !ok {
			continue
		}
		updated := commentReferenceElement.ReplaceAllString(string(content), "")
		updated = commentRangeElement.ReplaceAllString(updated, "")
		updated = removeTocBookmarks(updated)
		if updated != string(content) {
			pkg.Set(name, []byte(updated))
			changed++
		}
	}
	if _, ok := pkg.Get("word/comments.xml"); ok {
		pkg.Delete("word/comments.xml")
		changed++
	}
	if content, ok := pkg.Get(documentRelationshipsTarget); ok {
		updated := commentsRelationship.ReplaceAllString(string(content), "")
		if updated != string(content) {
			pkg.Set(documentRelationshipsTarget, []byte(updated))
			changed++
		}
	}
	if content, ok := pkg.Get(contentTypesTarget); ok {
		updated := commentsContentType.ReplaceAllString(string(content), "")
		if updated != string(content) {
			pkg.Set(contentTypesTarget, []byte(updated))
			changed++
		}
	}
	return changed
}

// removeTocBookmarks removes __RefHeading___Toc bookmark pairs from XML content.
// These bookmarks are auto-generated by Word to support TOC hyperlinks. After
// template-in-place repair they become orphaned (the heading structure changes)
// and must be stripped together with their paired bookmarkEnd elements.
// Only bookmarkEnd elements whose w:id matches a removed __RefHeading___Toc
// bookmarkStart are deleted; other bookmarks are left intact.
func removeTocBookmarks(content string) string {
	matches := tocBookmarkStartRe.FindAllStringSubmatch(content, -1)
	if len(matches) == 0 {
		return content
	}
	tocIDs := make(map[string]bool, len(matches))
	for _, m := range matches {
		tocIDs[m[1]] = true
	}
	content = tocBookmarkStartRe.ReplaceAllString(content, "")
	content = bookmarkEndRe.ReplaceAllStringFunc(content, func(s string) string {
		sub := bookmarkEndRe.FindStringSubmatch(s)
		if sub != nil && tocIDs[sub[1]] {
			return ""
		}
		return s
	})
	return content
}
