package formatchecker

func CommonThesisStandard() FormatStandard {
	return FormatStandard{
		Name:        "高校论文通用要求基线",
		Description: "各高校论文格式的通用要求与核心共识",
		PageSetup: PageSetup{
			PaperSize:      "A4",
			MarginTop:      2.5,
			MarginBottom:   2.5,
			MarginLeft:     2.5,
			MarginRight:    2.5,
			HeaderDistance: 1.6,
			FooterDistance: 2.0,
		},
		HeadingStyles: []HeadingStyle{
			{
				Level:         1,
				Name:          "一级标题",
				FontName:      "黑体",
				FontSize:      16,
				Bold:          true,
				Alignment:     "center",
				SpacingBefore: 24,
				SpacingAfter:  18,
				LineSpacing:   22,
			},
			{
				Level:         2,
				Name:          "二级标题",
				FontName:      "黑体",
				FontSize:      15,
				Bold:          true,
				Alignment:     "left",
				SpacingBefore: 20,
				SpacingAfter:  16,
				LineSpacing:   22,
			},
			{
				Level:         3,
				Name:          "三级标题",
				FontName:      "黑体",
				FontSize:      14,
				Bold:          true,
				Alignment:     "left",
				SpacingBefore: 18,
				SpacingAfter:  14,
				LineSpacing:   22,
			},
		},
		ParagraphStyles: []ParagraphStyle{
			{
				Name:            "正文",
				FontName:        "宋体",
				FontSize:        12,
				Alignment:       "justify",
				LineSpacing:     22,
				FirstLineIndent: 2,
				SpacingBefore:   0,
				SpacingAfter:    0,
			},
			{
				Name:            "英文字体",
				FontName:        "Times New Roman",
				FontSize:        12,
				Alignment:       "justify",
				LineSpacing:     22,
				FirstLineIndent: 2,
				SpacingBefore:   0,
				SpacingAfter:    0,
			},
		},
		TableStyle: TableStyle{
			CaptionPrefix:   "表",
			FontName:        "宋体",
			FontSize:        10.5,
			CaptionPosition: "top",
			BorderStyle:     "three-line",
		},
		FigureStyle: FigureStyle{
			CaptionPrefix:   "图",
			FontName:        "宋体",
			FontSize:        10.5,
			CaptionPosition: "bottom",
		},
		ReferenceStyle: ReferenceStyle{
			Style:        "GB/T 7714-2015",
			FontName:     "宋体",
			FontSize:     10.5,
			LineSpacing:  18,
			IndentFormat: "hanging",
		},
		AbstractStyles: []AbstractStyle{
			{
				Type:           "chinese",
				Heading:        "摘要",
				FontName:       "宋体",
				FontSize:       12,
				Bold:           false,
				Alignment:      "justify",
				LineSpacing:    22,
				KeywordsPrefix: "关键词",
			},
			{
				Type:           "english",
				Heading:        "Abstract",
				FontName:       "Times New Roman",
				FontSize:       12,
				Bold:           false,
				Alignment:      "justify",
				LineSpacing:    22,
				KeywordsPrefix: "Keywords",
			},
		},
	}
}
