package formatchecker

func CQCECStandard() FormatStandard {
	return FormatStandard{
		Name:        "重庆工程学院本科毕业论文格式标准",
		Description: "重庆工程学院本科毕业设计（论文）格式规范（2024版）",
		PageSetup: PageSetup{
			PaperSize:      "A4",
			MarginTop:      2.5,
			MarginBottom:   2.5,
			MarginLeft:     2.5,
			MarginRight:    2.5,
			HeaderDistance: 1.6,
			FooterDistance: 2.1,
		},
		HeadingStyles: []HeadingStyle{
			{
				Level:         1,
				Name:          "一级标题（章）",
				FontName:      "黑体",
				FontSize:      16,
				Bold:          true,
				Alignment:     "center",
				SpacingBefore: 24,
				SpacingAfter:  18,
				LineSpacing:   20,
			},
			{
				Level:         2,
				Name:          "二级标题（节）",
				FontName:      "黑体",
				FontSize:      15,
				Bold:          true,
				Alignment:     "left",
				SpacingBefore: 20,
				SpacingAfter:  16,
				LineSpacing:   20,
			},
			{
				Level:         3,
				Name:          "三级标题（条）",
				FontName:      "黑体",
				FontSize:      14,
				Bold:          true,
				Alignment:     "left",
				SpacingBefore: 18,
				SpacingAfter:  14,
				LineSpacing:   20,
				IndentRight:   2,
			},
			{
				Level:         4,
				Name:          "四级标题",
				FontName:      "宋体",
				FontSize:      12,
				Bold:          false,
				Alignment:     "left",
				SpacingBefore: 16,
				SpacingAfter:  12,
				LineSpacing:   20,
				IndentRight:   2,
			},
			{
				Level:         5,
				Name:          "五级标题",
				FontName:      "宋体",
				FontSize:      12,
				Bold:          false,
				Alignment:     "left",
				SpacingBefore: 14,
				SpacingAfter:  10,
				LineSpacing:   20,
				IndentRight:   2,
			},
			{
				Level:         6,
				Name:          "六级标题",
				FontName:      "宋体",
				FontSize:      12,
				Bold:          false,
				Alignment:     "left",
				SpacingBefore: 12,
				SpacingAfter:  8,
				LineSpacing:   20,
				IndentRight:   2,
			},
		},
		ParagraphStyles: []ParagraphStyle{
			{
				Name:            "正文",
				FontName:        "宋体",
				FontSize:        12,
				Alignment:       "justify",
				LineSpacing:     20,
				FirstLineIndent: 2,
				SpacingBefore:   0,
				SpacingAfter:    0,
			},
			{
				Name:            "摘要正文",
				FontName:        "宋体",
				FontSize:        12,
				Alignment:       "justify",
				LineSpacing:     20,
				FirstLineIndent: 2,
				SpacingBefore:   0,
				SpacingAfter:    0,
			},
		},
		TableStyle: TableStyle{
			CaptionPrefix:   "表",
			FontName:        "宋体",
			FontSize:        10.5,
			CaptionPosition: "top",
			BorderStyle:     "all_borders",
		},
		FigureStyle: FigureStyle{
			CaptionPrefix:   "图",
			FontName:        "宋体",
			FontSize:        10.5,
			CaptionPosition: "bottom",
		},
		ReferenceStyle: ReferenceStyle{
			Style:        "GB/T 7714",
			FontName:     "宋体",
			FontSize:     10.5,
			LineSpacing:  20,
			IndentFormat: "hanging_indent",
		},
		AbstractStyles: []AbstractStyle{
			{
				Type:           "chinese",
				Heading:        "摘要",
				FontName:       "宋体",
				FontSize:       14,
				Bold:           true,
				Alignment:      "center",
				LineSpacing:    20,
				KeywordsPrefix: "关键词：",
			},
			{
				Type:           "english",
				Heading:        "Abstract",
				FontName:       "Times New Roman",
				FontSize:       14,
				Bold:           true,
				Alignment:      "center",
				LineSpacing:    20,
				KeywordsPrefix: "Keywords: ",
			},
		},
	}
}
